# Generated by Django 6.0 on 2025-12-08 11:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_card_last_learned_card_learned_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='learning_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='next_review_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
