# Generated by Django 6.0 on 2025-12-08 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_card_learning_level_card_next_review_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_decks', to=settings.AUTH_USER_MODEL),
        ),
    ]
