# Generated by Django 6.0 on 2025-12-11 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_deck_shared_with'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
